# Generated by Django 5.0.14 on 2026-05-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=60, unique=True)),
                ('correo', models.EmailField(max_length=160, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargaRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_ok', models.IntegerField(default=0)),
                ('filas_error', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'carga_recaudacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colegiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=160, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=160)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('foto_url', models.CharField(max_length=500)),
                ('nro_colegiado', models.CharField(max_length=5)),
                ('colegiado_desde', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colegiado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCORPORACION', 'INCORPORACION'), ('MENSUALIDAD', 'MENSUALIDAD')], max_length=20)),
                ('periodo', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('canal', models.CharField(choices=[('CAJA', 'CAJA'), ('ARCHIVO_RECAUDACION', 'ARCHIVO_RECAUDACION')], max_length=30)),
                ('metodo', models.CharField(blank=True, max_length=30, null=True)),
                ('nro_operacion', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_pago', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=160)),
                ('correo', models.EmailField(max_length=160)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('foto_url', models.CharField(max_length=500)),
                ('titulo_pdf_url', models.CharField(max_length=500)),
                ('recibo_pago_url', models.CharField(max_length=500)),
                ('firma_url', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('EN_REVISION', 'EN_REVISION'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA')], default='EN_REVISION', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoVoucherPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodos_json', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia Bancaria')], max_length=20)),
                ('voucher', models.FileField(upload_to='vouchers/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('nro_referencia', models.CharField(blank=True, max_length=40)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('colegiado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.colegiado')),
            ],
            options={
                'db_table': 'pago_voucher_pendiente',
            },
        ),
    ]
