# Generated by Django 5.0.14 on 2026-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
    ]
