# Generated by Django 5.0.14 on 2026-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administrador_rol_administrador_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_operacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
