# Generated by Django 5.0.14 on 2026-07-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitud_fecha_pago_solicitud_numero_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='cuenta_confirmada',
            field=models.BooleanField(default=True),
        ),
    ]
