# Generated by Django 5.0.14 on 2026-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitud_fecha_pago_solicitud_numero_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegiado',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='colegiado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
