# Generated by Django 5.0.14 on 2026-07-18 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_colegiado_celular_colegiado_correo_solicitud_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('en_uso_hasta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caja_pos',
            },
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='administrador',
            name='cuenta_confirmada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 18, 8, 43, 28, 114483, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
