# Generated by Django 5.0.14 on 2026-07-20 01:15

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cajapos_remove_administrador_creado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagovoucherpendiente',
            name='voucher',
            field=models.FileField(storage=utils.storage.select_raw_storage, upload_to='vouchers/'),
        ),
    ]
