# Generated by Django 5.0.14 on 2026-07-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_creado_en_administrador_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='origen',
            field=models.CharField(default='WEB', max_length=20),
        ),
    ]
