# Generated by Django 5.0.14 on 2026-07-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pagovoucherpendiente_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='dni_anverso_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='dni_reverso_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
