# Generated by Django 5.0.14 on 2026-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitud_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='metodo_pago',
            field=models.CharField(blank=True, default='TRANSFERENCIA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recibo_pago_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
