# Generated by Django 5.0.14 on 2026-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitud_dni_anverso_url_solicitud_dni_reverso_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='origen',
            field=models.CharField(default='WEB', max_length=20),
        ),
    ]
