# Generated by Django 5.0.14 on 2026-07-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitud_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='razon_social_factura',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ruc_factura',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_comprobante',
            field=models.CharField(default='03', max_length=2),
        ),
    ]
