# Generated by Django 5.0.14 on 2026-05-23 03:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colegiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos.', regex='^[0-9]{8}$')])),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El celular debe tener exactamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('cip', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El CIP debe tener exactamente 5 dígitos.', regex='^[0-9]{5}$')])),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_activa', models.BooleanField(default=False)),
                ('token_activacion', models.CharField(blank=True, max_length=100, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_colegiatura', models.DateField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colegiados', to='finanzas.carrera')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colegiados', to='finanzas.sede')),
            ],
            options={
                'verbose_name': 'Colegiado',
                'verbose_name_plural': 'Colegiados',
                'ordering': ['-fecha_colegiatura', 'nombre_completo'],
                'unique_together': {('cip', 'sede')},
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_cobro', models.IntegerField()),
                ('anio_cobro', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('colegiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='finanzas.colegiado')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-anio_cobro', '-mes_cobro'],
                'unique_together': {('colegiado', 'mes_cobro', 'anio_cobro')},
            },
        ),
    ]
