# Generated by Django 5.0.14 on 2026-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegiado',
            name='dni',
        ),
        migrations.AddField(
            model_name='colegiado',
            name='numero_documento',
            field=models.CharField(default='0', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colegiado',
            name='tipo_colegiado',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Vitalicio', 'Vitalicio'), ('Temporal', 'Temporal')], default='Ordinario', max_length=20),
        ),
        migrations.AddField(
            model_name='colegiado',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CIP', 'Reg. CIP'), ('RUC', 'RUC'), ('PASS', 'Pasaporte'), ('CE', 'Carné de Extranjería')], default='DNI', max_length=10),
        ),
    ]
