# Generated by Django 5.0.14 on 2026-07-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_colegiado_dni_colegiado_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora_pago', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('PRESENCIAL', 'Pago Presencial'), ('ONLINE', 'Pago Online')], default='PRESENCIAL', max_length=20)),
                ('metodo_pago', models.CharField(default='EFECTIVO', help_text='EFECTIVO, TARJETA, TRANSFERENCIA, YAPE, PLIN, etc.', max_length=50)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('DESCARGADO', 'Descargado'), ('ENVIADO', 'Enviado')], default='GENERADO', max_length=20)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('colegiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='finanzas.colegiado')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='finanzas.cuota')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_hora_pago'],
                'indexes': [models.Index(fields=['colegiado', '-fecha_hora_pago'], name='finanzas_co_colegia_091d60_idx'), models.Index(fields=['numero_comprobante'], name='finanzas_co_numero__230c30_idx')],
            },
        ),
    ]
