# Generated by Django 5.0.14 on 2026-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='sunat_correlativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='sunat_estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='sunat_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='sunat_mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='sunat_serie',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='sunat_tipo_comprobante',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta')], default='03', max_length=2),
        ),
    ]
