# Generated by Django 5.0.14 on 2026-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_comprobante_sunat_correlativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
