# Generated by Django 5.0.14 on 2026-07-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_comprobante_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colegiado',
            unique_together={('cip', 'carrera', 'sede')},
        ),
    ]
