# Generated by Django 5.0.14 on 2026-07-16 03:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0003_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramiteInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='8 dígitos del DNI', max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos.', regex='^[0-9]{8}$')])),
                ('nombre_completo', models.CharField(help_text='Nombre y apellido del postulante', max_length=150)),
                ('correo', models.EmailField(help_text='Correo electrónico de contacto', max_length=100)),
                ('celular', models.CharField(help_text='Número de celular (9 dígitos)', max_length=9, validators=[django.core.validators.RegexValidator(message='El celular debe tener exactamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('foto', models.ImageField(blank=True, help_text='Foto del postulante (JPG/PNG)', null=True, upload_to='tramites/fotos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('titulo_pdf', models.FileField(blank=True, help_text='Copia del título profesional (PDF)', null=True, upload_to='tramites/titulos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('voucher', models.FileField(blank=True, help_text='Comprobante de pago (PDF/JPG/PNG)', null=True, upload_to='tramites/vouchers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('numero_operacion', models.CharField(blank=True, help_text='Número de operación del comprobante', max_length=50, null=True)),
                ('banco', models.CharField(choices=[('BN', 'Banco de la Nación'), ('BCP', 'Banco de Crédito del Perú (BCP)'), ('BBVA', 'BBVA'), ('SCOTIABANK', 'Scotiabank'), ('INTERBANK', 'Interbank'), ('OTROS', 'Otros')], default='BN', help_text='Banco donde se realizó el pago', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en la que se realizó el pago', null=True)),
                ('foto_url', models.URLField(blank=True, help_text='URL externa de la foto (si se usa almacenamiento en la nube)', max_length=500, null=True)),
                ('titulo_pdf_url', models.URLField(blank=True, help_text='URL externa del título (si se usa almacenamiento en la nube)', max_length=500, null=True)),
                ('voucher_url', models.URLField(blank=True, help_text='URL externa del voucher (si se usa almacenamiento en la nube)', max_length=500, null=True)),
                ('firma_url', models.URLField(blank=True, help_text='URL externa de la firma (si se usa almacenamiento en la nube)', max_length=500, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', help_text='Estado actual del trámite', max_length=15)),
                ('observacion', models.TextField(blank=True, help_text='Observaciones del revisor (si aplica)', null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
                ('carrera', models.ForeignKey(help_text='Carrera a la que aplica', on_delete=django.db.models.deletion.PROTECT, related_name='tramites_inscripcion', to='finanzas.carrera')),
                ('sede', models.ForeignKey(help_text='Sede donde solicita inscripción', on_delete=django.db.models.deletion.PROTECT, related_name='tramites_inscripcion', to='finanzas.sede')),
            ],
            options={
                'verbose_name': 'Trámite de Inscripción',
                'verbose_name_plural': 'Trámites de Inscripción',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['dni'], name='tramites_tr_dni_f1fbaf_idx'), models.Index(fields=['estado'], name='tramites_tr_estado_622a56_idx'), models.Index(fields=['fecha_solicitud'], name='tramites_tr_fecha_s_3dd6f9_idx'), models.Index(fields=['carrera', 'sede'], name='tramites_tr_carrera_0821d6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tramiteinscripcion',
            constraint=models.UniqueConstraint(fields=('numero_operacion', 'banco', 'fecha_pago'), name='unique_comprobante_tramite'),
        ),
    ]
