# Generated by Django 5.0.14 on 2026-07-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoBancoNacionMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(help_text='Número de operación generado por el banco', max_length=50, unique=True)),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el depósito')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto depositado', max_digits=8)),
                ('usado', models.BooleanField(default=False, help_text='Indica si este pago ya fue reclamado en el sistema')),
            ],
            options={
                'verbose_name': 'Mock Pago Banco de la Nación',
                'verbose_name_plural': 'Mock Pagos Banco de la Nación',
                'db_table': 'mock_banco_nacion',
            },
        ),
    ]
