# Generated by Django 5.0.14 on 2026-07-20 01:15

import django.core.validators
import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_pagobanconacionmock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramiteinscripcion',
            name='titulo_pdf',
            field=models.FileField(blank=True, help_text='Copia del título profesional (PDF)', null=True, storage=utils.storage.select_raw_storage, upload_to='tramites/titulos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='tramiteinscripcion',
            name='voucher',
            field=models.FileField(blank=True, help_text='Comprobante de pago (PDF/JPG/PNG)', null=True, storage=utils.storage.select_raw_storage, upload_to='tramites/vouchers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
