# Generated by Django 5.0.14 on 2026-07-20 01:45

import django.core.validators
import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_alter_tramiteinscripcion_titulo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteinscripcion',
            name='dni_anverso',
            field=models.FileField(blank=True, help_text='Anverso del DNI (PDF/JPG/PNG)', null=True, storage=utils.storage.select_raw_storage, upload_to='tramites/dni/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='tramiteinscripcion',
            name='dni_reverso',
            field=models.FileField(blank=True, help_text='Reverso del DNI (PDF/JPG/PNG)', null=True, storage=utils.storage.select_raw_storage, upload_to='tramites/dni/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
